### ISSUE TITLE
speedtest is written to disk, which gives incorrect results

### ISSUE THREAD

**Issue by zamarax** [jackyaz/spdMerlin#28]
Hi, came across an issue, kind of.

So I set this up and found that the download / upload file is written to disk vs memory.

Most people to keep things neat will use the ports in the back of their router which is USB2.0, this is giving drastically lower results then what I actually have, capping out at roughly 400mbps where as my service is 1.5gbps/1.0gbps, can you adjust the script to use the routers memory to read / write from and not the attached disk?

By comparison I can run a browser test at the same time the router test is running and it will report back nearly 1.0gbps (the other 400-500mbps being used by the router test).

**Comment by jackyaz** [comment]
Outside of my control. It leverages Ookla's closed source binary, you'll need to ask them if this is possible. https://www.speedtest.net/apps/cli
